language: java

script:
  - java -jar ./bin/yuicompressor-2.4.8.jar -o '.css$:-min.css' ./css/*.css

deploy:
  provider: s3
  access_key_id: ${AWS_ACCESS_KEY_ID}
  secret_access_key: ${AWS_SECRET_ACCESS_KEY}
  bucket: "takatsu-travisci/${TRAVIS_BRANCH}"
  skip_cleanup: true

notifications:
  slack: travis-ci-takatsuji:lQnY4FuwYnhOPNh7egoZXbtb
