language: java

script:
  - java -jar ./bin/yuicompressor-2.4.8.jar -o '.css$:-min.css' ./css/*.css

deploy:
  provider: s3
  access_key_id: "AKIAISE6DV3IMDH3GDGQ"
  secret_access_key: "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"
  bucket: "takatsu-travisci"

notifications:
  slack: travis-ci-takatsuji:lQnY4FuwYnhOPNh7egoZXbtb
